### ISSUE TITLE
Rejecting a specimen

### ISSUE THREAD

**Issue by ereng** [ilabafrica/blis-kenya#3]
Is rejecting a specimen still an option? It is missing.

**Comment by kitsao** [comment]
Yes it is. I'm fixing it.

On Mon, Feb 17, 2014 at 4:58 PM, ereng notifications@github.com wrote:

> Is rejecting a specimen still an option? It is missing.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ilabafrica/BLIS-Kenya/issues/3
> .

## 

_Kitsao+254 728 830 678+254 731 607 650+254 750 422 990+254 735 108 101P.O.
Box 1024 - 80108, Kilifi, Kenya.P.O. Box 2736 - 00100, Nairobi, kenya._

**Comment by mapesa** [comment]
Reject feature is still unavailable for some tests. Does it transmit the info (on rejection) back to Sanitas?

**Comment by mapesa** [comment]
A specimen can still be rejected up until the time the test is done i.e. any time before the results have been posted. We should factor this in somehow. The information should trickle back to the patient (if we need to get another specimen) and/or doctor (if he needs to request the test again).

**Comment by kitsao** [comment]
Specimen are drawn and rejected/acceptef at the lab. I asked the lab guys
about this and the answer was that most rejected specimen are either
referred or from inpatients. Think of it, inpatients specimen are drawn by
the sisters who then take the specimen to the lab. If rejected, the sister
will draw another specimen...which is rare. As for referrals, if a specimen
is rejected, the person who brought the specimen will be given the
rejection report to warrant action on their side. This is easy because all
referred specimen are registered at the lab, including the tests...they are
not ordered directly by the clinicians at either Bungoma or Kapsabet
District Hospitals.

**Comment by mapesa** [comment]
Okay. Sounds convincing. I've closed the issue. If there's any improvement needed we can always reopen it or start another one.
